# Generated by Django 3.2.5 on 2021-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
